name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_release_windows_32:
    name: Release build (Win32, static Qt 5.6.3)
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3 
      - name: Get Qt 5.6.3
        uses: actions/checkout@v3
        with:
          repository: LongSoft/qt-5.6.3-static-x86-msvc2017
          path: qt5
          lfs: true
      - name: Unpack Qt 5.6.3
        shell: bash
        working-directory: qt5
        run: 7z x qt-5.6.3-static-x86-msvc2017.7z -o../..
      - name: Install v141_xp Toolset
        shell: powershell
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $WorkLoads = '--add Microsoft.VisualStudio.Component.WinXP'
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -eq 0) {
              Write-Host "components have been successfully added"
          } else {
              Write-Host "components were not installed"
          }
      - name: Create dist directory
        shell: bash
        run: mkdir dist

      - name: Create UEFIPatch build directory
        run: cmake -E make_directory ${{runner.workspace}}/build/UEFIPatch
      - name: Configure UEFIPatch
        shell: bash
        working-directory: ${{runner.workspace}}/build/UEFIPatch
        run: ../../qt-5.6.3-static-x86-msvc2017/bin/qmake.exe ../../UEFITool/UEFIPatch/
      - name: Build UEFIPatch
        working-directory: ${{runner.workspace}}/build/UEFIPatch
        shell: cmd
        run: |
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
            msbuild -t:Rebuild -p:PlatformToolset=v141_xp;Configuration=Release
      - name: Archive UEFIPatch
        working-directory: ${{runner.workspace}}/build/UEFIPatch/Release
        shell: bash
        run: |
          UEFITOOL_VER=$(cat ../../../UEFITool/version.h | grep PROGRAM_VERSION | cut -d'"' -f2 ) ; \
          7z a ../../../UEFITool/dist/UEFIPatch_${UEFITOOL_VER}_win32.zip UEFIPatch.exe
          
      - name: Create UEFIReplace build directory
        run: cmake -E make_directory ${{runner.workspace}}/build/UEFIReplace
      - name: Configure UEFIReplace
        working-directory: ${{runner.workspace}}/build/UEFIReplace
        shell: bash
        run: ../../qt-5.6.3-static-x86-msvc2017/bin/qmake.exe ../../UEFITool/UEFIReplace/
      - name: Build UEFIReplace
        working-directory: ${{runner.workspace}}/build/UEFIReplace
        shell: cmd
        run: |
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
            msbuild -t:Rebuild -p:PlatformToolset=v141_xp;Configuration=Release
      - name: Archive UEFIReplace
        working-directory: ${{runner.workspace}}/build/UEFIReplace/Release
        shell: bash
        run: |
          UEFITOOL_VER=$(cat ../../../UEFITool/version.h | grep PROGRAM_VERSION | cut -d'"' -f2) ; \
          7z a ../../../UEFITool/dist/UEFIReplace_${UEFITOOL_VER}_win32.zip UEFIReplace.exe

      - name: Create UEFITool build directory
        run: cmake -E make_directory ${{runner.workspace}}/build/UEFITool
      - name: Configure UEFITool
        shell: bash
        working-directory: ${{runner.workspace}}/build/UEFITool
        run: ../../qt-5.6.3-static-x86-msvc2017/bin/qmake.exe -tp vc ../../UEFITool/
      - name: Build UEFITool
        working-directory: ${{runner.workspace}}/build/UEFITool
        shell: cmd
        run: |
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
            msbuild -t:Rebuild -p:PlatformToolset=v141_xp;Configuration=Release
      - name: Archive UEFITool
        working-directory: ${{runner.workspace}}/build/UEFITool/release
        shell: bash
        run: |
          UEFITOOL_VER=$(cat ../../../UEFITool/version.h | grep PROGRAM_VERSION | cut -d'"' -f2) ; \
          7z a ../../../UEFITool/dist/UEFITool_${UEFITOOL_VER}_win32.zip UEFITool.exe
      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows 32-bit builds
          path: dist/*.zip
      - name: Upload to releases
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.zip
          tag: ${{ github.ref }}
          file_glob: true
